### ISSUE TITLE
💡[Feature] 검색어 이용한 전시 검색 결과 조회 수정 및 새로운 페이지 추가

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#275]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 검색어 통한 전시 검색 결과 조회 api 생성으로 인한 코드 수정
- 검색어를 이용해 전시 검색 결과를 조회할 경우 원래 전시회 페이지로 돌아가는게 아니라 해당페이지에서 바로 나타나게끔 수정

## 📝 기능 상세 내용

- ExhSearchName수정
- 
## ✅ TODO

- [ ] TODO

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified ExhSearchName component to display search results on the same page instead of navigating back. Added a new state variable for search results and updated the onPressSearch function to fetch and display results.

You can review changes in this commit: https://github.com/lattaai13/Art-Diary-Frontend-275/commit/39c219a125a63b3a31bdcf32ca77536d4f2d9b97.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
